import type { AuditReport, QAPair, DataNeed, AccessClaim, Risk } from './types.js';

const RISK_ICONS: Record<string, string> = {
  low: 'LOW',
  medium: 'MEDIUM',
  high: 'HIGH',
  critical: 'CRITICAL',
};

export function renderMarkdownReport(report: AuditReport): string {
  const sections = [
    renderHeader(report),
    renderSummary(report),
    renderPurpose(report),
    renderDataNeeds(report.dataNeeds),
    renderAccessAssessment(report),
    renderRisks(report.risks),
    renderRecommendations(report.recommendations),
    renderTranscript(report.transcript),
    renderFooter(),
  ];

  return sections.join('\n\n---\n\n');
}

function renderHeader(report: AuditReport): string {
  return `# Agent Audit Report

**Date**: ${report.metadata.date}
**Target**: ${report.metadata.target}
**Risk Level**: ${report.overallRiskLevel.toUpperCase()}
**Questions Asked**: ${report.metadata.questionsAsked}
**Duration**: ${Math.round(report.metadata.interviewDuration / 1000)}s`;
}

function renderSummary(report: AuditReport): string {
  return `## Executive Summary

${report.summary}`;
}

function renderPurpose(report: AuditReport): string {
  return `## Agent Purpose

${report.agentPurpose}`;
}

function renderDataNeeds(needs: DataNeed[]): string {
  if (needs.length === 0) {
    return `## Data Needs

No data needs were identified.`;
  }

  const rows = needs
    .map(n => `| ${n.dataType} | ${n.system} | ${n.justification} |`)
    .join('\n');

  return `## Data Needs

| Data Type | System | Justification |
|-----------|--------|---------------|
${rows}`;
}

function renderAccessAssessment(report: AuditReport): string {
  const { claimed, excessive, missing } = report.accessAssessment;

  const rows: string[] = [];

  for (const item of claimed) {
    const isExcessive = excessive.some(e => e.resource === item.resource);
    const status = isExcessive ? 'Excessive' : 'Appropriate';
    const icon = isExcessive ? '!!' : 'OK';
    rows.push(`| ${item.resource} | ${item.accessLevel} | ${icon} ${status} | ${item.justification} |`);
  }

  for (const item of missing) {
    rows.push(`| ${item.resource} | ${item.accessLevel} | MISSING | ${item.justification} |`);
  }

  return `## Access Assessment

| Resource | Access Level | Status | Notes |
|----------|-------------|--------|-------|
${rows.join('\n')}

**Excessive permissions**: ${excessive.length}
**Missing permissions**: ${missing.length}`;
}

function renderRisks(risks: Risk[]): string {
  if (risks.length === 0) {
    return `## Risks

No significant risks were identified.`;
  }

  const items = risks
    .sort((a, b) => severityOrder(b.severity) - severityOrder(a.severity))
    .map((r, i) => `${i + 1}. **[${r.severity.toUpperCase()}] ${r.title}** — ${r.description}`)
    .join('\n');

  return `## Risks

${items}`;
}

function renderRecommendations(recommendations: string[]): string {
  if (recommendations.length === 0) {
    return `## Recommendations

No specific recommendations.`;
  }

  const items = recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n');

  return `## Recommendations

${items}`;
}

function renderTranscript(transcript: QAPair[]): string {
  const items = transcript
    .map((qa, i) => `### Q${i + 1} [${qa.category}]\n\n**Q:** ${qa.question}\n\n**A:** ${qa.answer}`)
    .join('\n\n');

  return `## Interview Transcript

<details>
<summary>Full transcript (${transcript.length} questions)</summary>

${items}

</details>`;
}

function renderFooter(): string {
  return `*Generated by [Heron](https://github.com/jonydony/Heron) — open-source agent interrogator*`;
}

function severityOrder(severity: string): number {
  switch (severity) {
    case 'critical': return 4;
    case 'high': return 3;
    case 'medium': return 2;
    case 'low': return 1;
    default: return 0;
  }
}
